<template>
  <!-- //// Neoffice — when the on-prem Collabora (WOPI) backend is available, Office
       files open straight in the collaborative editor (read-only iframe when the
       user lacks write access).
       Upstream's Microsoft viewer stays as the fallback, but ONLY on an instance
       that has no Collabora at all: it ships the document to
       view.officeapps.live.com. When WOPI is enabled here, a document must never
       leave for Microsoft just because coolwsd is still waking up — it is stopped
       after 15 idle minutes, and a cold start can outrun the 20 s probe. We keep
       waiting instead, and offer a download if it truly never comes up. //// -->
  <CollaboraEditor v-if="collabora === true" :preview-entity="previewEntity" @error="collabora = false" />
  <div v-else-if="collabora === null" class="w-full h-full flex flex-col items-center justify-center gap-3">
    <LucideLoaderCircle class="size-7 animate-spin text-ink-gray-6" />
    <span v-if="waking" class="text-p-sm text-ink-gray-6">{{ __('Starting the editor…') }}</span>
  </div>
  <!-- //// Neoffice — WOPI is on but Collabora never answered: say so and offer the
       file, rather than routing it to an external service behind the user's back. -->
  <div
    v-else-if="wopiEnabled"
    class="max-w-[450px] h-fit self-center p-10 bg-surface-base rounded-4 text-2xl-medium text-center shadow-xl flex flex-col justify-center items-center gap-4"
  >
    <LucideAlertCircle class="size-10" />
    <span class="text-ink-gray-8">{{ __('The editor is unavailable') }}</span>
    <span class="text-p-base text-center text-ink-gray-7">
      {{ __('The document editor did not start. Your document has not left this server.') }}
    </span>
    <div class="flex flex-col gap-2 w-full">
      <Button class="w-full" variant="subtle" @click="retry">{{ __('Try again') }}</Button>
      <Button class="w-full" variant="solid" @click="download">{{ __('Download') }}</Button>
    </div>
  </div>
  <!-- //// Neoffice — v-if became v-else-if: this Microsoft viewer is now the LAST
       //// branch, reached only on an instance with no Collabora at all (see the
       //// WOPI branches above). A document must never leave for
       //// view.officeapps.live.com just because coolwsd is still starting. //// -->
  <iframe
    v-else-if="warned && jwt_token"
    :src="'https://view.officeapps.live.com/op/embed.aspx?src=' + srcUrl"
    class="w-4/5 mx-auto h-full"
    frameborder="0"
  >
    This is an embedded Microsoft Office document, powered by Office Online>.</iframe
  >
  <div
    v-else
    class="max-w-[450px] h-fit self-center p-10 bg-surface-base rounded-4 text-2xl-medium text-center shadow-xl flex flex-col justify-center items-center gap-4"
  >
    <div v-if="error" class="text-p-base">
      <LucideSettings class="size-8 mb-6 mx-auto" />
      Please ask your site's administrator to set the access key in the
      <a href="/app/drive-disk-settings" class="underline">Settings</a>.
    </div>
    <template v-else>
      <LucideAlertCircle class="size-10" />
      <span class="text-ink-gray-8">Are you sure you want to preview?</span>
      <span class="text-p-base text-center text-ink-gray-7">
        This preview is generated by an external service (<b>Microsoft</b>), not by Drive. For extra
        privacy, we'd suggest downloading.
      </span>
      <div class="flex flex-col gap-2 w-full">
        <Button class="w-full" variant="subtle" :loading="jwt_token === ''" @click="warned = true">
          View anyway
        </Button>
        <Button class="w-full" variant="solid" @click="download"> Download </Button>
      </div>
    </template>
  </div>
</template>
<script setup>
//// Neoffice — createResource / onMounted / CollaboraEditor / the spinner icon are
//// ours: they drive the WOPI probe and the on-prem editor added above.
import { Button, createResource } from 'frappe-ui'
import { computed, onMounted, ref, watch } from 'vue'
import CollaboraEditor from '@/apps/drive/components/FileTypePreview/CollaboraEditor.vue'
import LucideLoaderCircle from '~icons/lucide/loader-circle'
const props = defineProps({
  previewEntity: Object,
})

//// Neoffice — null = probing, true = Collabora available, false = not available.
//// `wopiEnabled` says whether this instance is SUPPOSED to have Collabora, which
//// is what decides between "keep waiting / offer a download" and upstream's
//// Microsoft viewer. A cold coolwsd is retried a few times before giving up:
//// the daemon is stopped after 15 idle minutes, so the first document opened in
//// a while routinely lands mid-start.
const collabora = ref(null)
const wopiEnabled = ref(false)
const waking = ref(false)
const MAX_PROBES = 6
const PROBE_DELAY_MS = 2500
let probes = 0

const canEdit = createResource({
  url: 'suite.drive.wopi.editor.can_edit_file',
  onSuccess(data) {
    wopiEnabled.value = !!data?.wopi_enabled
    if (data?.can_edit) {
      collabora.value = true
      return
    }
    if (data?.retryable && probes < MAX_PROBES) {
      probes += 1
      waking.value = true
      setTimeout(probe, PROBE_DELAY_MS)
      return
    }
    collabora.value = false
  },
  onError() {
    collabora.value = false
  },
})

function probe() {
  canEdit.submit({ file_id: props.previewEntity.name })
}

function retry() {
  probes = 0
  collabora.value = null
  probe()
}

onMounted(probe)

const warned = ref(false)
watch(warned, async () => {
  jwt_token.value = ''
  const res = await fetch(
    '/api/method/suite.drive.api.files.create_auth_token?entity_name=' + props.previewEntity.name
  )
  const { message } = JSON.parse(await res.text())
  if (message) {
    jwt_token.value = message
  } else {
    error.value = 'Please set up your Drive Settings.'
  }
})

const jwt_token = ref(null)
const error = ref(null)
const srcUrl = computed(() =>
  encodeURIComponent(
    new URL(
      `/api/method/suite.drive.api.files.get_file_content?token=${jwt_token.value}&entity_name=${props.previewEntity.name}&trigger_download=1`,
      window.location.origin
    ).href
  )
)
const download = () => (window.location.ref = srcUrl.value)
</script>
